### ISSUE TITLE
Is collaboration still possible?

### ISSUE THREAD

**Issue by Davido101** [jtalbert123/Cell-Lab-Remake#6]
I have a small team (3 people including me) of people who could help. Even if you're not working on this anymore yourself I'd like to contribute to the project. Could I ask you to be added to the project? If that isn't already too much to ask, I'd like to be able to contact you

**Comment by jtalbert123** [comment]
Sure. Feel free to email ***@***.***

I'll have to figure out how to add anyone. Honestly been ages since I've
done anything.

**Comment by Davido101** [comment]
Your email was censored by GitHub
