### ISSUE TITLE
Are donations possible?

### ISSUE THREAD

**Issue by Davido101** [jtalbert123/Cell-Lab-Remake#8]
I'm asking here because this is still the only way I have to talk to you other than email which I'm not sure you'll even see (though I guess I could say the same about issues in this repository). I've been working on a remake behind the scenes with a friend (in a different repository) and we were in agreement that it was gonna be free but we were also wondering if we could get donations considering this is a remake of another game. Do you know anything about that?

**Comment by jtalbert123** [comment]
You'd have to talk to petters.
